name: CI_All

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, AGX]
        include:
          - os: ubuntu-20.04
            BUILDER_PREP_CMD: "sudo apt-get update -qq && sudo apt-get -y install   autoconf   automake  autopoint build-essential  cmake   git-core   libass-dev   libfreetype6-dev   libgnutls28-dev   libmp3lame-dev   libsdl2-dev   libtool   libsoup-gnome2.4-dev   libva-dev   libvdpau-dev   libvorbis-dev   libxcb1-dev   libxcb-shm0-dev   libxcb-xfixes0-dev   ninja-build   pkg-config   texinfo   wget   yasm   zlib1g-dev   nasm   gperf  bison && pip3 install meson"
            VCPKG_BOOTSTRAP_CMD: "./vcpkg/bootstrap-vcpkg.sh"
            GST_BUILD_SCRIPT: "thirdparty/build_gstreamer.sh"
            GST_BUILD_COMMAND: "sh build_gstreamer.sh"
            CACHE_PATH: "~/.cache/vcpkg/archives"
            FLAV: "Linux"
            VCPKG_FILE: "base/vcpkg.nocuda.json"
            CMAKE-CONF: "cmake -B . -DENABLE_CUDA=OFF ../base"
            NPROC: 3
            SHELL: "bash"
          - os: AGX
            BUILDER_PREP_CMD: "echo No builder prep required"
            VCPKG_BOOTSTRAP_CMD: "./vcpkg/bootstrap-vcpkg.sh"
            CACHE_PATH: "~/.cache/vcpkg/archives"
            FLAV: "Linux_ARM64"
            VCPKG_FILE: "base/vcpkg.cuda.json"
            CMAKE-CONF: "export VCPKG_FORCE_SYSTEM_BINARIES=1 && cmake -B . -DENABLE_ARM64=ON ../base"
            NPROC: 7
            SHELL: "bash"
    env:
      BUILD_TYPE: RelWithDebInfo
      CACHE_REST_KEY: ${{ matrix.FLAV }}-build-cache-vcpkg
      TEST_RES_XML: CI_test_result_${{ matrix.FLAV }}.xml

    steps:
    - name: Install build dependencies in cloud hosted env
      run: ${{ matrix.BUILDER_PREP_CMD }}
    
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        submodules: 'false'

    - name: Checkout submodule
      run: |
        git submodule update --init --recursive 
        git submodule status > submodule_ver.txt
      
    - name: Run VCPKG bootstrap
      run: ${{ matrix.VCPKG_BOOTSTRAP_CMD }}

    - name: Cache dependencies for fast cloud build
      id: cache-all
      if: runner.arch != 'ARM64' # let's not cache from self hosted runner as it is caching anyways
      uses: actions/cache@v2
      with:
          path: |
            ${{ matrix.CACHE_PATH }}
            ${{github.workspace}}/thirdparty/gst-build/gst-build-1.16/outInstall/
          key:  ${{ env.CACHE_REST_KEY }}-${{ hashFiles( matrix.VCPKG_FILE, matrix.GST_BUILD_SCRIPT, 'base/CMakeLists.txt', 'vcpkg/baseline.json', 'submodule_ver.txt') }}
          restore-keys: ${{ env.CACHE_REST_KEY }}-

    - name: Build Gstreamer
      if: ${{ runner.arch != 'ARM64' && steps.cache-all.outputs.cache-hit != 'true' }}
      working-directory: ${{github.workspace}}/thirdparty
      run: ${{matrix.GST_BUILD_COMMAND}}

    - name: Build libmp4
      working-directory: ${{github.workspace}}/thirdparty/libmp4
      run: sh build.cmd
          
    - name: Make build folder
      run: mkdir -p build
      continue-on-error: true

    - name: Configure CMake Common
      working-directory: ${{github.workspace}}/build
      run: |
        cp -f ../${{matrix.VCPKG_FILE}} ../base/vcpkg.json 
        ${{ matrix.CMAKE-CONF }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGHA=ON -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake
      continue-on-error: false
      
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{env.BUILD_TYPE}} -j ${{ matrix.NPROC }}
      continue-on-error: false
      
    - name: Test Linux
      if: runner.os == 'Linux'
      env:
        LD_LIBRARY_PATH: ${{github.workspace}}/thirdparty/gst-build/gst-build-1.16/outInstall/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH      
      run: build/aprapipesut --log_format=JUNIT --log_sink=${{ env.TEST_RES_XML }} -p -l all
      timeout-minutes: 10
      
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: TestResults_${{ matrix.FLAV }}
        path: |
          ${{ env.TEST_RES_XML }}

    - name: Upload build logs 
      if:  ${{ failure() }} # only upload logs when we have a fialure above
      uses: actions/upload-artifact@v3
      with:
        name: BuildLogs_${{ matrix.FLAV }}
        path: |
          ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
          ${{ github.workspace }}/vcpkg/buildtrees/**/*.txt
  
  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: build
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Display structure of downloaded files
        working-directory: artifacts
        run: ls -R
      - name: Publish Linux_x64 Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: artifacts/TestResults_Linux/CI_test_result*.xml
          check_name: Linux_x64 No Cuda Test Results
      - name: Publish Linux_ARM64 Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: artifacts/TestResults_Linux_ARM64/CI_test_result*.xml
          check_name: Linux_ARM64 Test Results

