FROM nvidia/cuda:11.8.0-devel-ubuntu20.04
RUN apt-get update -qq && apt-get -y install \
    ca-certificates curl zip unzip tar autoconf automake autopoint build-essential flex git-core \
    libass-dev libfreetype6-dev libgnutls28-dev libmp3lame-dev libsdl2-dev libtool libsoup-gnome2.4-dev \
    libva-dev libvdpau-dev libvorbis-dev libxdamage-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev \
    libncurses5-dev libncursesw5-dev ninja-build pkg-config texinfo wget yasm zlib1g-dev nasm gperf \
    bison python3 python3-pip dos2unix libgles2-mesa-dev libxcursor-dev \
    libglu1-mesa-dev python3-jinja2 && pip3 install jinja2 meson cmake==3.29.6 && \
    apt-get purge -y man-db && \
    rm -rf /usr/share/man /usr/share/doc /usr/share/doc-base && \
    rm -rf /var/lib/apt/lists/*
