# ============================================================
# cmake/ScanModuleClasses.cmake
# Scans header files for Module subclasses
# Used by D2 Phase 3: Missing Registration Detection
# ============================================================

# Find all header files
file(GLOB_RECURSE HEADERS "${SCAN_DIR}/*.h")

set(MODULE_CLASSES "")

foreach(header ${HEADERS})
    file(READ "${header}" content)

    # Replace newlines with spaces for simpler matching
    string(REGEX REPLACE "\n" " " content "${content}")
    string(REGEX REPLACE "\r" " " content "${content}")

    # Match patterns like "class ClassName : public Module" where Module is at word boundary
    # This requires the class name to be immediately after "class " keyword
    string(REGEX MATCHALL "class ([A-Za-z_][A-Za-z0-9_]*) *(:| *final *:)[^;{]*public +Module[^A-Za-z0-9_]" matches "${content}")

    foreach(match ${matches})
        # Extract class name - it's the first word after "class "
        string(REGEX REPLACE "class +([A-Za-z_][A-Za-z0-9_]*).*" "\\1" classname "${match}")

        # Skip abstract base classes and internal classes
        if(NOT classname MATCHES "^(Module|AbsControlModule|NvTransformBase|ModuleProps)$")
            # Class name must start with uppercase (all module classes do)
            if(classname MATCHES "^[A-Z]")
                list(APPEND MODULE_CLASSES "${classname}")
            endif()
        endif()
    endforeach()
endforeach()

# Remove duplicates
list(REMOVE_DUPLICATES MODULE_CLASSES)
list(SORT MODULE_CLASSES)

# Count modules
list(LENGTH MODULE_CLASSES MODULE_COUNT)

# Generate the output file
set(OUTPUT_CONTENT "// Auto-generated by cmake/ScanModuleClasses.cmake\n")
set(OUTPUT_CONTENT "${OUTPUT_CONTENT}// Total modules found: ${MODULE_COUNT}\n")
set(OUTPUT_CONTENT "${OUTPUT_CONTENT}// Re-run 'cmake --build . --target scan-modules' to update\n\n")
set(OUTPUT_CONTENT "${OUTPUT_CONTENT}namespace {\n")
set(OUTPUT_CONTENT "${OUTPUT_CONTENT}    const std::vector<std::string> ALL_MODULE_SUBCLASSES = {\n")

foreach(classname ${MODULE_CLASSES})
    set(OUTPUT_CONTENT "${OUTPUT_CONTENT}        \"${classname}\",\n")
endforeach()

set(OUTPUT_CONTENT "${OUTPUT_CONTENT}    };\n")
set(OUTPUT_CONTENT "${OUTPUT_CONTENT}}\n")

file(WRITE "${OUTPUT_FILE}" "${OUTPUT_CONTENT}")

message(STATUS "Found ${MODULE_COUNT} Module subclasses")
