name: CI_All

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NOTE_TO_SELF: "environments can not be passed from here to reused workflows!"
  
jobs:
  win-nocuda-build-prep:
    uses: ./.github/workflows/build-test-win.yml
    with:
      is-prep-phase: true
  win-nocuda-build-test:
    needs: win-nocuda-build-prep
    uses: ./.github/workflows/build-test-win.yml
  win-nocuda-publish:
    needs: win-nocuda-build-test
    permissions:
      checks: write
      pull-requests: write
    uses: ./.github/workflows/publish-test.yml  
    with:
      flav: 'Windows'

  win-cuda-build-test:
    uses: ./.github/workflows/build-test-win.yml
    with:
      runner: windows-cuda
      cuda: 'ON'
      flav: 'Windows-cuda'
      is-selfhosted: true
      nProc: 8
      nTestTimeoutMins: 20
  win-cuda-publish:
    needs: win-cuda-build-test
    permissions:
      checks: write
      pull-requests: write
    uses: ./.github/workflows/publish-test.yml
    with:
      flav: 'Windows-cuda'
      
  jetson-build-test:
    uses: ./.github/workflows/build-test-lin.yml
    with:
      runner: AGX
      flav: Linux_ARM64
      cuda: 'ON'
      is-selfhosted: true
      prep-cmd: 'cmake --version ; ninja --version ; gcc --version ; nvcc --version ; git --version'
      cmake-conf-cmd: 'export VCPKG_FORCE_SYSTEM_BINARIES=1 && cmake -B . -DENABLE_ARM64=ON ../base'
      nProc: 6
  jetson-publish:
    needs: jetson-build-test
    permissions:
      checks: write
      pull-requests: write
    uses: ./.github/workflows/publish-test.yml
    with:
      flav: Linux_ARM64
  
  linux-nocuda-build-test:
    uses: ./.github/workflows/build-test-lin.yml
    with:
      flav: Linux
  linux-nocuda-publish:
    needs: linux-nocuda-build-test
    permissions:
      checks: write
      pull-requests: write
    uses: ./.github/workflows/publish-test.yml
    with:
      flav: Linux

  linux-cuda-build-no-test:
    container: ghcr.io/kumaakh/aprapipes-build-x86-ubutu18.04-cuda:latest
    uses: ./.github/workflows/build-test-lin.yml
    with:
      flav: Linux-Cuda
      skip-test: true 
      cuda: 'ON'
      prep-cmd: 'cmake --version ; ninja --version ; gcc --version ; meson --version ; nvcc --version ; git --version'
      cache-path: '/github/home/.cache/vcpkg/archives'

  
  

