name: Doxygen Action

on:
  push:
    branches: [ dOxy ]
  pull_request:
    branches: [ dOxy ]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        doxyfile-path: "./Doxyfile" 
        working-directory: "." 
    
    - name: Upload documentation artifact
      uses: actions/upload-artifact@v2
      with:
        name: html-documentation
        path: ./documentation/html
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentation/html